spring:
  application:
    name: immochallenge
  datasource:
    url: todo
    username: todo
    password: todo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: todo
    password: todo
    schemas: todo
    url: todo
    locations: classpath:db/migration
spotify:
  client-id: todo
  client-secret: todo
  artist-ids:
    - todo
    - todo