CREATE TABLE artist (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_modified timestamp(6) without time zone NULL,
    last_synchronized timestamp(6) without time zone NULL,
    spotify_id character varying(255) NOT NULL,
    href character varying(255) NULL,
    spotify_uri character varying(255) NULL
    external_url character varying(255) NULL,
    name character varying(255) NULL,
    followers bigint NOT NULL,
    genres character varying(255) NULL,
    popularity integer NOT NULL,
  );

CREATE TABLE artist_artist_images (
    artist_id bigint NOT NULL,
    url character varying(255) NULL
    height integer NULL,
    width integer NULL,
  );

CREATE INDEX idx_artist_name_lower ON artist(LOWER(name));