CREATE TABLE artist (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_modified timestamp(6) without time zone NULL,
    last_synchronized timestamp(6) without time zone NULL,
    spotify_id character varying(255) NOT NULL,
    name character varying(255) NULL,
    followers bigint NOT NULL,
    genres character varying(255) NULL,
    popularity integer NOT NULL,
    href character varying(255) NULL,
    spotify_uri character varying(255) NULL,
    external_url character varying(255) NULL
  );

  CREATE TABLE album (
      id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      last_modified timestamp(6) without time zone NULL,
      last_synchronized timestamp(6) without time zone NULL,
      spotify_id character varying(255) NOT NULL,
      name character varying(255) NULL,
      album_type character varying(255) NULL,
      total_tracks integer NOT NULL,
      release_date character varying(255) NULL,
      release_date_precision character varying(255) NULL,
      album_group character varying(255) NULL,
      restriction_reason character varying(255) NULL,
      href character varying(255) NULL,
      spotify_uri character varying(255) NULL,
      external_url character varying(255) NULL
    );

CREATE TABLE artist_images (
    artist_id bigint NOT NULL,
    url character varying(255) NULL,
    height integer NULL,
    width integer NULL
  );

CREATE TABLE album_images (
    album_id bigint NOT NULL,
    url character varying(255) NULL,
    height integer NULL,
    width integer NULL
  );

CREATE TABLE album_artists (
    album_id bigint NOT NULL,
    spotify_id character varying(255) NULL,
    name character varying(255) NULL,
    type character varying(255) NULL,
    href character varying(255) NULL,
    spotify_uri character varying(255) NULL,
    external_url character varying(255) NULL

  );

CREATE INDEX idx_artist_name_lower ON artist(LOWER(name));
CREATE INDEX idx_album_name_lower ON album(LOWER(name));