CREATE TABLE IF NOT EXISTS artist (
    popularity integer NOT NULL,
    followers bigint NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_modified timestamp(6) without time zone NULL,
    last_synchronized timestamp(6) without time zone NULL,
    external_url character varying(255) NULL,
    genres character varying(255) NULL,
    href character varying(255) NULL,
    name character varying(255) NULL,
    spotify_id character varying(255) NOT NULL,
    spotify_uri character varying(255) NULL
  );

CREATE TABLE IF NOT EXISTS artist_artist_images (
    height integer NULL,
    width integer NULL,
    artist_id bigint NOT NULL,
    url character varying(255) NULL
  );

  CREATE INDEX idx_artist_name_lower ON artist(LOWER(name));